name: Generate Docker Image

on: [push]

jobs:
  push to registry
    name: Setup Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/chechout@v2

      - name: Log in into Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}

      - name: Send image to Docker Hub
        uses: docker/build-push-actions@v2
        with:
          push: true
          tags: gildeir/api-marvel:latest
