name: Generate Docker Image

on: [push]

jobs:
  push_to_registry:
    name: Setup Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/chechout@v2

      - name: Log in into Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}

      - name: Send image to Docker Hub
        working-directory: ./
        run: |
          docker build -t gildeir/api-marvel:latest .
          docker push gildeir/api-marvel:latest

